version: "3.9"
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
    - "8443:8080"
    container_name: jenkins
    volumes:
      - "/mnt/c/devops_project/jenkins_volume/:/var/jenkins_home"
    env_file:
      - ./jenkins/jenkins.env
    networks:
      - app-network
  
  tomcat:
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    ports:
      - "9443:8080"
    container_name: tomcat-web
    volumes:
      - "/mnt/c/devops_project/tomcat_volume/webapps/:/usr/local/tomcat/webapps.dist/"
    networks:
      - app-network
  

networks:
  app-network:
    driver: bridge

